# App Resource Bundle (.arb) directory
arb-dir: lib/core/localization/l10n

# Set files template
template-arb-file: app_en.arb

# Generate localizations files
output-localization-file: app_localizations.dart